version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_prod
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: [ "CMD-SHELL", "mongosh --eval 'db.runCommand(\"ping\").ok' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  product-api:
    image: lengocan/product-api:latest
    container_name: product_api_prod
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/product_db
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:3000/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  mongo_data:
